# Generated by Django 4.2.24 on 2025-09-28 01:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=150)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google", "Google"),
                            ("meta", "Meta"),
                            ("cohere", "Cohere"),
                            ("mistral", "Mistral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("openrouter_model_id", models.CharField(max_length=150)),
                ("supports_vision", models.BooleanField(default=False)),
                ("supports_function_calling", models.BooleanField(default=False)),
                ("supports_streaming", models.BooleanField(default=True)),
                ("max_context_length", models.PositiveIntegerField()),
                ("max_output_tokens", models.PositiveIntegerField()),
                (
                    "input_price_per_million",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                (
                    "output_price_per_million",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("requires_subscription", models.BooleanField(default=False)),
                ("min_subscription_tier", models.CharField(blank=True, max_length=20)),
                ("average_response_time_ms", models.PositiveIntegerField(default=0)),
                ("reliability_score", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UsageTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_used", models.CharField(max_length=100)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("embedding", "Embedding"),
                            ("memory", "Memory"),
                        ],
                        max_length=50,
                    ),
                ),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("response_time_ms", models.PositiveIntegerField(default=0)),
                ("was_cached", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chats.chat",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chats.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConversationMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mem0_memory_id", models.CharField(max_length=255, unique=True)),
                ("total_memories", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("memory_summary", models.TextField(blank=True)),
                ("memory_decay_enabled", models.BooleanField(default=True)),
                ("max_memory_items", models.PositiveIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory",
                        to="chats.chat",
                    ),
                ),
            ],
        ),
    ]
