# Generated by Django 4.2.24 on 2025-09-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_integration", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConversationMemory",
        ),
    ]
