import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { AuthProvider } from "@/components/providers/auth-provider";
import { ClientLayoutProvider } from "@/components/providers/client-layout-provider"; // Assuming this is the correct path
import { QueryProvider } from "@/components/providers/query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sans ${GeistSans.variable} ${GeistMono.variable}`}>
        <QueryProvider>
          <AuthProvider>
            <ClientLayoutProvider>{children}</ClientLayoutProvider>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
