# Generated by Django 4.2.24 on 2025-09-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="shared_memory_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
