# Generated by Django 4.2.24 on 2025-09-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_shared_memory_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="shared_memory_id",
        ),
    ]
