# Generated by Django 4.2.24 on 2025-09-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="vector_id",
        ),
        migrations.AlterField(
            model_name="chat",
            name="model_used",
            field=models.CharField(default="gpt-4o-mini", max_length=100),
        ),
    ]
