# Generated by Django 4.2.24 on 2025-09-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_remove_vector_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="mem0_memory_id",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="qdrant_collection_id",
        ),
        migrations.RemoveField(
            model_name="message",
            name="mem0_reference",
        ),
    ]
